# Generated by Django 5.0.6 on 2024-06-09 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sub_unit', models.CharField(max_length=255)),
                ('pertanyaan', models.TextField()),
                ('telepon_fax', models.CharField(max_length=20)),
                ('koordinator', models.CharField(max_length=100)),
                ('jumlah_mesin', models.PositiveIntegerField()),
                ('potensi_ikm', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
