# Generated by Django 5.0.6 on 2024-06-17 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_responden'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnsurPelayanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_unsur', models.CharField(max_length=255)),
            ],
        ),
    ]
