# Generated by Django 5.0.6 on 2024-06-18 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kuesioner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isi_pertanyaan', models.TextField()),
                ('opsi_a', models.CharField(max_length=255)),
                ('opsi_b', models.CharField(max_length=255)),
                ('opsi_c', models.CharField(max_length=255)),
                ('opsi_d', models.CharField(max_length=255)),
            ],
        ),
    ]
