# Generated by Django 5.0.6 on 2024-06-18 06:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_kuesioner'),
    ]

    operations = [
        migrations.AddField(
            model_name='responden',
            name='tanggal_survey',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
