# Generated by Django 5.0.6 on 2024-06-18 19:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_alter_responden_tanggal_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.CharField(max_length=255)),
                ('tanggal_survey', models.DateField(default=django.utils.timezone.now)),
                ('pertanyaan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.kuesioner')),
                ('responden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.responden')),
            ],
        ),
    ]
