# Generated by Django 5.0.6 on 2024-06-21 19:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_jawabankuesioner_delete_surveyresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layanan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_layanan', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='kuesioner',
            name='layanan',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='website.layanan'),
            preserve_default=False,
        ),
    ]
