# Generated by Django 5.0.6 on 2024-06-23 09:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_layanan_kuesioner_layanan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responden',
            name='medsos',
        ),
        migrations.AddField(
            model_name='responden',
            name='jenis_layanan',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='website.layanan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='subunit',
            name='jenis_layanan',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='website.layanan'),
            preserve_default=False,
        ),
    ]
